### ISSUE TITLE
ext_apps on conda-forge

### ISSUE THREAD

**Issue by marieBvr** [jhcepas/ext_apps#6]
Hi @jhcepas,
I would like to make ete3 external apps available on conda-forge (or bioconda). 
I know it is already available on the etetoolkit channel, but I cannot use this channel for tool integration in the Galaxy platform.
Would you agree?

Sincerely
Marie

**Comment by jhcepas** [comment]
Hi Marie,
thanks for getting in touch!

Yes, this is no problem at all. Actually, most (probably all) external
tools are already in bioconda. This change is something we have also
considered for the new ete4 version.
cheers,
-jaime

**Comment by marieBvr** [comment]
Great, I will work on it then.
Thanks,
Marie
